### ISSUE TITLE
How to run this plugin locally without commiting.

### ISSUE THREAD

**Issue by THEBOSS0369** [sumn2u/gitbook-plugin-ace-editor#1]
Hey @sumn2u ! How do i run this plugin like i'm doing npm start and then this is occuring i think this is the plugin that's why it probably won't start but then how can i see the changes i will be doing, like in the previous gitbook-theme plugin i had to just code one interpreter with one style so there wasn't any need for previewing. Also you mentioned to add plugin in book.json, there is no book.json file in this repo so do i have to create a book.json and add the plugin into it? or is there any other way i can run the gitbook plugin locally. I tried to npm start this came
`npm start
npm error Missing script: "start"
npm error
npm error Did you mean one of these?
npm error   npm star # Mark your favorite packages
npm error   npm stars # View packages marked as favorites
npm error
npm error To see a list of scripts, run:
npm error   npm run`

**Comment by sumn2u** [comment]
@THEBOSS0369  Please have a look into this.

https://stackoverflow.com/questions/30897205/create-a-gitbook-plugin-locally-without-publishing-it

Basically, you have to link the local version of the package as described here.

https://medium.com/@AidThompsin/how-to-npm-link-to-a-local-version-of-your-dependency-84e82126667a

**Comment by THEBOSS0369** [comment]
@sumn2u Thanks Man! this will help. I will keep this issue open until I develop the interpreter fully as there is no discussion section in this repo.

**Comment by THEBOSS0369** [comment]
Closing this issue as it is not required anytime soon.
